-- Schema base para MySQL/cPanel
-- Prefijo solicitado: abogapp2
-- Nota: la tabla de usuarios se fija como abogapp_users

CREATE TABLE IF NOT EXISTS `abogapp_users` (
  `id` VARCHAR(80) PRIMARY KEY,
  `email` VARCHAR(190) NOT NULL,
  `nombre` VARCHAR(190) NOT NULL,
  `telefono` VARCHAR(50) DEFAULT '',
  `role` VARCHAR(80) DEFAULT 'Abogado',
  `password_hash` VARCHAR(255) NOT NULL,
  `is_admin` TINYINT(1) NOT NULL DEFAULT 0,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `abogapp2_clientes` (
  `id` VARCHAR(80) PRIMARY KEY,
  `payload` LONGTEXT NOT NULL,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `abogapp2_asuntos` (
  `id` VARCHAR(80) PRIMARY KEY,
  `payload` LONGTEXT NOT NULL,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `abogapp2_causas` (
  `id` VARCHAR(80) PRIMARY KEY,
  `payload` LONGTEXT NOT NULL,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `abogapp2_tareas` (
  `id` VARCHAR(80) PRIMARY KEY,
  `payload` LONGTEXT NOT NULL,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `abogapp2_plazos` (
  `id` VARCHAR(80) PRIMARY KEY,
  `payload` LONGTEXT NOT NULL,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `abogapp2_cotizaciones` (
  `id` VARCHAR(80) PRIMARY KEY,
  `payload` LONGTEXT NOT NULL,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `abogapp2_logs` (
  `id` VARCHAR(80) PRIMARY KEY,
  `payload` LONGTEXT NOT NULL,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `abogapp2_meta` (
  `meta_key` VARCHAR(80) PRIMARY KEY,
  `meta_value` LONGTEXT NOT NULL,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
